### PR TITLE
Fall back to `sh` on non-Windows

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes https://github.com/actions/upload-pages-artifact/issues/13

### CODE REVIEW

**Comment by yoannchaudet** [comment]
Will get that merged after https://github.com/actions/upload-pages-artifact/pull/16 which adds some tests so we don't regress anything.

**Comment by JamesMGreene** [comment]
My suspicion is that we would actually be safer by just _not_ specifying the shell and allow Actions to try for the `bash` executable and then fallback to `sh` if it wasn't found. The documentation seems to read like specifying `bash` explicitly will also fallback like that but it sounds like that may not be the case based on the report in #13. 🤔

**Comment by ncfavier** [comment]
Weirdly enough, removing `shell` in the action fails: https://github.com/ncfavier/1lab/runs/7919247403?check_suite_focus=true

**Comment by JamesMGreene** [comment]
Ah, yeah, there it is in [the docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsshell). 🔍 

> ### `runs.steps[*].shell`
> **Optional** The shell where you want to run the command. You can use any of the shells listed here. 👉🏻 _Required if `run` is set._ 👈🏻

**Comment by ncfavier** [comment]
Any updates on this?

**Review by yoannchaudet — APPROVED** [review]
🚀 !

**Pull request merged**
